 const comics = [
    {   series: 'Web of Spider-Man',
        issue: '3',
        description: "Even iron bars cannot contain the Vulture, as Adrian Toomes pulls off a wily prison break…followed by a mad dash for the Vulturions! Spidey intervenes when Vulture’s mad quest over intellectual property takes off on a dangerous course.",
        releaseDate: "June 01, 1985",
        coverArt: "src/assets/web-of-spider-man-3.jpg",
        webLink: "https://www.marvel.com/comics/issue/12025/web_of_spider-man_1985_3",
    },
    {
        series: "Thor (2014)",
        issue: "7",
        description: "The battle for the Hammer rages on! Behold, the All-New Thor vs. the unstoppable machine of death and destruction that is... The Destroyer. Most verily, 'tis 'nuff said.",
        releaseDate: "April 15, 2015",
        coverArt: "src/assets/thor-2014-7.jpg",
        webLink: "https://www.marvel.com/comics/issue/52819/thor_2014_7",
    },
    {
        series: "Uncanny X-Men",
        issue: "173",
        description: "Wolverine and Rogue crack some Yakuza skulls in a Ginza District bar. Their goal: to pick up the trail that will lead them to the Silver Samurai and Viper!",
        releaseDate: "September 01, 1983",
        coverArt: "src/assets/x-men-173.jpg",
        webLink: "https://www.marvel.com/comics/issue/13714/uncanny_x-men_1963_173",
    },
    {
        series: "Daredevil",
        issue: "191", 
        description: "Daredevil plays a little game of Russian Roulette with a hospitalized Bullseye. Has DD finally gone too far in his quest for vengeance? Matt Murdock is a changed man, and not for the better.", 
        releaseDate: "February 01, 1983", 
        coverArt: "src/assets/daredevil-191.jpg",
        webLink: "https://www.marvel.com/comics/issue/8175/daredevil_1964_191",
    },
    {
        series: "Avengers",
        issue: "71", 
        description: "Thanks to Kang, the Avengers are still hurtling through time. Some of the team does battle in 4000 AD, while Black Panther, Yellowjacket, and the Vision go up against the original Invaders in 1941 France!", 
        releaseDate: "December 01, 1969", 
        coverArt: "src/assets/avengers-71.jpg",
        webLink: "https://www.marvel.com/comics/issue/7323/avengers_1963_71",
    },
    {
        series: "Fantastic Four",
        issue: "245", 
        description: "Sue endures a pesky interview, followed by an attack on the Baxter Building! Will Sue save her teammates from this unidentified yet strangely familiar attacker?", 
        releaseDate: "August 01, 1982", 
        coverArt: "src/assets/fantastic-four-245.jpg",
        webLink: "https://www.marvel.com/comics/issue/13056/fantastic_four_1961_245",
    },
    {
        series: "Runaways (2003)",
        issue: "1", 
        description: "Featured Characters: Alex Wilder, Runaways", 
        releaseDate: "April 16, 2003", 
        coverArt: "src/assets/runaways-2003-1.jpg",
        webLink: "https://www.marvel.com/comics/issue/15061/runaways_2003_1",
    },
    {
        series: "Doctor Strange, Socerer Supreme",
        issue: "19", 
        description: "He has faced Dormammu, Nightmare, and even Mephisto himself! But even Doctor Strange cannot escape the wrath of AZRAEL, Angel of Death!", 
        releaseDate: "July 01, 1990", 
        coverArt: "src/assets/doctor-strange-sorcerer-supreme-19.jpg",
        webLink: "https://www.marvel.com/comics/issue/20178",
    },
    {
        series: "Marvel Zombies (2005)",
        issue: "2", 
        description: "Appearing in their first starring series - the Marvel Zombies! On an Earth inhabited by zombified versions of Marvel's greatest heroes, a ray of hope has appeared-the space-born Silver Surfer! Still, can even a being wielding the Power Cosmic long survive among the denizens of this undead world?", 
        releaseDate: "January 04, 2006", 
        coverArt: "src/assets/marvel-zombies-2005-2.jpg",
        webLink: "https://www.marvel.com/comics/issue/3430/marvel_zombies_2005_2",
    },
    {
        series: "Ms. Marvel (2014)",
        issue: "12", 
        description: "Love is in Jersey City as Valentine's Day arrives! Kamala Khan may not be allowed to go to the dance, but Ms. Marvel is! Well sort of - by crashing it attempting to capture Asgard's most annoying trickster! Yup, it's a special Valentine's Day issue featuring Marvel's favorite charlatan, Loki!", 
        releaseDate: "February 18, 2015", 
        coverArt: "src/assets/ms-marvel-2014-12.jpg",
        webLink: "https://www.marvel.com/comics/issue/49100/ms_marvel_2014_12",
    },
    {
        series: "Human Torch Comics (1940)",
        issue: "5", 
        description: "The Human Torch and Sub-Mariner battle it out in a fight to the death!", 
        releaseDate: "June 01, 1941", 
        coverArt: "src/assets/human-torch-comics-5.jpg",
        webLink: "https://www.marvel.com/comics/issue/8863/human_torch_comics_1940_5",
    },
    {
        series: "Journey Into Mystery",
        issue: "83", 
        description: "Introducing... the Mighty Thor! The most exciting Super Hero of all time! When the Stone-Men from Saturn invade Earth, only Dr. Donald Blake can stop them -- but he stands no chance, not until he strikes a wooden stick on the ground and finds himself transformed into Thor, God of Thunder! Watch as Thor learns how to wield his hammer in battle! Only this new hero can save the Earth from being conquered!", 
        releaseDate: "August 01, 1962", 
        coverArt: "src/assets/journey-into-mystery-83.jpg",
        webLink: "https://www.marvel.com/comics/issue/9779/journey_into_mystery_1952_83",
    },
    {
        series: "Marvel Comics",
        issue: "1", 
        description: "The one that started it all, featuring the first appearances of both the the android Human Torch and the Sub-Mariner!", 
        releaseDate: "August 31, 1939", 
        coverArt: "src/assets/marvel-comics-1.jpg",
        webLink: "https://www.marvel.com/comics/issue/10008/marvel_comics_1939_1",
    },
];
export default comics;